# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('userPicture', models.ImageField(null=True, upload_to=b'img')),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('remark', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
