# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learns',
            name='uid',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='uid',
            field=models.CharField(default=111, max_length=20),
            preserve_default=False,
        ),
    ]
