# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lovewall',
            name='images',
            field=models.ImageField(null=True, upload_to='learn_img'),
        ),
        migrations.AddField(
            model_name='lovewall',
            name='tosb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teasingwall',
            name='images',
            field=models.ImageField(null=True, upload_to='learn_img'),
        ),
        migrations.AddField(
            model_name='teasingwall',
            name='title',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lovewall',
            name='content',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
