# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPicture',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
