# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0002_auto_20170412_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teasingwall',
            old_name='title',
            new_name='tosb',
        ),
    ]
