# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0002_auto_20170406_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_Learns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critisID', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comments_Lovewall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critisID', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comments_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critisID', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comments_Teasingwall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critisID', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Learns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=2000)),
                ('images', models.ImageField(null=True, upload_to='news-img')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('like', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lovewall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=2000)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=2000)),
                ('images', models.ImageField(null=True, upload_to='news-img')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('like', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teasingwall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=2000)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
