# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0003_auto_20170412_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='lovewall',
            name='formsb',
            field=models.CharField(default=23, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teasingwall',
            name='formsb',
            field=models.CharField(default=213, max_length=20),
            preserve_default=False,
        ),
    ]
