# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0003_comments_learns_comments_lovewall_comments_news_comments_teasingwall_learns_lovewall_news_teasingwal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='like',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
