# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0004_auto_20170410_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learns',
            name='like',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPicture',
            field=models.ImageField(null=True, upload_to='user_img'),
        ),
    ]
