# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0004_auto_20170416_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_learns',
            name='critisID',
            field=models.CharField(max_length=20),
        ),
    ]
