# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0004_auto_20170413_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lovewall',
            old_name='formsb',
            new_name='fromsb',
        ),
    ]
