# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0005_auto_20170416_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='learns',
            name='counts',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='counts',
            field=models.IntegerField(null=True),
        ),
    ]
