# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0006_auto_20170412_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_news',
            name='images',
            field=models.ImageField(null=True, upload_to='news_img'),
        ),
    ]
