# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0007_comments_news_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_news',
            name='newID',
            field=models.IntegerField(null=True),
        ),
    ]
