# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0007_auto_20170416_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments_learns',
            name='counts',
        ),
        migrations.RemoveField(
            model_name='comments_news',
            name='counts',
        ),
        migrations.AddField(
            model_name='learns',
            name='counts',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='counts',
            field=models.IntegerField(null=True),
        ),
    ]
