# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0008_comments_news_newid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments_news',
            old_name='newID',
            new_name='newsID',
        ),
    ]
