# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0009_auto_20170416_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='counts',
            field=models.IntegerField(default=0),
        ),
    ]
