# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0011_auto_20170416_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learns',
            old_name='like',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='like',
            new_name='likes',
        ),
    ]
