# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0012_auto_20170417_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learns',
            name='counts',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='learns',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
