# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0012_auto_20170414_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_news',
            name='critisID',
            field=models.CharField(max_length=20),
        ),
    ]
