# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0013_auto_20170417_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('critisID', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='mycampus.User')),
                ('new_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycampus.News')),
            ],
        ),
    ]
