# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0016_auto_20170414_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments_news',
            name='new',
        ),
        migrations.AddField(
            model_name='comments_news',
            name='new_id',
            field=models.IntegerField(null=True),
        ),
    ]
