# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0017_auto_20170414_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_news',
            name='new_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycampus.News'),
        ),
    ]
