# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0017_merge_20170418_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_like',
            name='critis',
        ),
        migrations.RemoveField(
            model_name='news_like',
            name='new',
        ),
        migrations.AddField(
            model_name='learns',
            name='like',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='news_like',
            name='critisID',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='news_like',
            name='new_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comments_news',
            name='critisID',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
