# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0020_childcomments_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildComments_Learns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critisID', models.CharField(max_length=20, null=True)),
                ('learn_id', models.IntegerField(null=True)),
                ('comment_id', models.IntegerField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=255, null=True)),
                ('images', models.ImageField(null=True, upload_to='news_img')),
            ],
        ),
    ]
