# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0021_childcomments_learns'),
    ]

    operations = [
        migrations.AddField(
            model_name='learns',
            name='publisher_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mycampus.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='publisher_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mycampus.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='publisher',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
