# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0022_auto_20170422_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcomments_news',
            name='father_Comments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mycampus.Comments_News'),
            preserve_default=False,
        ),
    ]
