# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycampus', '0023_childcomments_news_father_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_news',
            name='ifchild',
            field=models.IntegerField(default=0),
        ),
    ]
